---
title: "Brownlows Bets"
author: "Monica Avila"
date: "put the date here"
output: html_document: default
 ---

<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

 At the first day of class there are 35 students in Math Statistics class and professor Brownlow always proposes this bet to his students "I will wager $2 to your bet of $1 that at least two people in today's class have  the same birthday.  He tells me he has made that bet 1137 times so far. Where do you think his profits are? Discuss this in a markdown document

I will make a sequence to represent the students and their birthdays that Brownlow made bets with, to get the statistics if any of them shared their birthday. I will also use this information to detemind Brownlows possible 
profits and losses. 

# Methods

<!--Decide on your methods:  In this section explain the approach you will take to attack the issue --- how will you decide on a likely estimate of professor Brownlow's earnings or losses after 1137 bets. Also explain how you construct a 95% confidence interval about your estimate of his winnings !-->

I will first make A sequence on numbers from 1-365 to represent all the possible birthdays the students have. Then I will make another sequence of 35 to represent the students in the class and use that as a sample from the 365. I will put this data into a function that will allow me to reuse the data multiple times. The function will give me the results of brownlows bets, that includes how much money he wins and how many birthdays were repeated. 


#Profit Estimate

<!--Explain and display the results of your method of coming up with the estimate of professor Brownlows betting!-->


# Confidence interval of Brownlows earning

<!--Explain and display your method of coming up with a 95% confidence interval of  professor Brownlows-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If professor Brownlow is consistantly making or losing money how could he change his payout so that his profits center on zero?  Also discuss what size his class should be in order to have his current scheme balance at zero profit.!-->

